# 构建镜像
# 这里假设Vue应用构建后的dist文件夹放在当前目录下
# 需要进入包含这个dist文件夹的目录并运行
# docker build -t unicorn .
# docker run -d -p 80:80 -p 443:443 unicorn
# docker run -d -p 80:80 unicorn
# 使用node作为基础镜像
FROM node:23-alpine

# 设置工作目录
WORKDIR /app

# 安装node依赖
COPY package*.json ./
RUN npm install

# 拷贝源代码
COPY src /app/src


# 暴露端口
EXPOSE 5001



## # 运行express
CMD ["node", "/app/src/server/index.mjs"]
